### ISSUE TITLE
Random and Procedural map generation ideas - roads and rectangle city blocks

### ISSUE THREAD

**Issue by thadguidry** [FullScreenShenanigans/EightBittr#274]
## Overview

Given that @JoshuaKGoldberg states in his blog post:
> I want to finally make it performant and have a good level editor & random map generation support as first party modules.

We should:
Beyond simple uninteresting [Random Tile Grids](https://github.com/gilles-leblanc/gameproject), I think that Tensor Fields and L-systems would be a nice addition.
It would be nice to have basic module support for random city blocks or areas/zones (sometimes called districts).
It would be nice to eventually have parameter control to support Radial center or Polyline paths or branching rules.

## Best ideas and research I have seen
- https://martindevans.me/game-development/2015/12/11/Procedural-Generation-For-Dummies-Roads/
- https://gamedev.stackexchange.com/questions/122015/how-to-generate-a-city-street-network
- http://www.diva-portal.org/smash/get/diva2:1119094/FULLTEXT02.pdf

# Example projects
- Tensor Fields - https://github.com/ProbableTrain/MapGenerator
- ...

**Comment by JoshuaKGoldberg** [comment]
Hey thanks for the writeup & links @thadguidry, much appreciated! I'm going to move this to a discussion since it's not yet actionable in the core game engine but has content we definitely should look into. 

In general, my vision for EightBittr is that this is a very bare-bones game engine, providing only the core parts used by the vast majority of consumers. It would be very reasonable that EightBittr provides the ability to specify how a random map would be generated, then a consuming module builds on top of that.

As to how that would look... no clue yet 😄
