### ISSUE TITLE
🐛 Bug: "yarn compile -w" requires Typescript installed

### ISSUE THREAD

**Issue by codewithjulie** [FullScreenShenanigans/EightBittr#322]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/FullScreenShenanigans/EightBittr/issues?q=is%3Aissue+label%3A%22type%3A+bug%22) and found none that matched my issue.

### Expected

While following along in the walkthrough, as stated in the [Package Setup](https://github.com/FullScreenShenanigans/EightBittr/blob/main/docs/walkthrough/1.%20Package%20Setup.md), you should be able to run `yarn compile -w` without any errors

### Actual

I found out that I did not have Typescript installed as I was getting this error  `/bin/sh: tsc: command not found`

### Additional Info

after installing Typescript using `npm i typescript` I was able to run the `yarn compile -w` command

**Comment by JoshuaKGoldberg** [comment]
Grr, I can never keep track of which command variants use the local installed package command vs. rely on a global one. This is a good first tooling issue: accepting PRs to fix the setup `package.json`'s `"compile"` script to use `yarn tsc` instead of the global `tsc`.

Here are the relevant templates used to fill in `package.json` files in `shenanigans-manager`'s `hydrate` command:

https://github.com/FullScreenShenanigans/EightBittr/blob/c1f961e3d47353a8da9d71b1ab46f95e8d34155d/packages/shenanigans-manager/setup/package-external.json#L18

https://github.com/FullScreenShenanigans/EightBittr/blob/c1f961e3d47353a8da9d71b1ab46f95e8d34155d/packages/shenanigans-manager/setup/package-internal.json#L3

Thanks for filing @codewithjulie! 🔥

**Comment by JoshuaKGoldberg** [comment]
@codewithjulie I think this might be an environment-specific thing? Do you have Yarn installed globally?

```plaintext
josh ~/repos/EightBittr $ typescript
zsh: command not found: typescript
josh ~/repos/EightBittr $ which typescript
typescript not found
josh ~/repos/EightBittr $ yarn compile
yarn run v1.22.19
$ tsc -b
✨  Done in 0.22s.
```

Works on my machine. But, if you can point out anything that this repo should do differently, I'd be happy to reopen this issue and take another look. Thanks!
